### ISSUE TITLE
opendev 中的CaptainHook 编译动态库 not work

### ISSUE THREAD

**Issue by baxiang** [liang8305/answer-vibration#1]
在ios7.1条件下编译出来 answer-vibration.dylib 不执行 没有任何作用，是不是我的配置需要修改 还是CaptainHook 不支持在ios7.1条件下编译

**Comment by pangliang** [comment]
7.1我还真没试过, 我的是7.04; 如果你是自己编译的话, 估计需要手动在cydia安装下 preferenceloader;
如果还不行, 你试试用 我的源来安装看看: http://www.zhaoxiaodan.com/cydia/

**Comment by baxiang** [comment]
从cydia下载了 的确不能使用了 我的机型5c 系统7.11

**Comment by pangliang** [comment]
hello, 我更新了一下, 用7.1.2测试了可以使用了; 也更新了README, 你可以按照来进行编译试试; 也可以用源的最新版本安装试试
